# Generated by Django 3.1.2 on 2021-04-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythontutorials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
