# Generated by Django 3.1.2 on 2021-04-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythontutorials', '0003_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
