# Generated by Django 3.1.2 on 2021-04-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210411_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
